image: node:dubnium-alpine

variables:
  DEPLOYER_TAG: "registry.gitlab.com/rphovley-templates/node-api-express-objection-postgres/deployer"

stages:
  - dependencies
  - lint
  - build
  - staging
  - production

cache:
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  script:
    - yarn
  only:
    changes:
      - package.json

deployer-dependencies:
  stage: dependencies
  tags:
    - deployer
  script:
    - yarn
  only:
    changes:
      - package.json

build:
  stage: build
  script:
    - yarn lint # I have included this in the same stage because of stage overhead (30 seconds per stage)
    - ls
    # - yarn compile # whatever command(s) to build the project

deploy_staging:
  stage: staging
  image: $DEPLOYER_TAG
  tags:
    - deployer
  when: on_success
  environment: staging
  script:
    - echo $DEPLOYER_SERVICE_ACCOUNT | xxd -r -p - > /tmp/$CI_PIPELINE_ID.json # translate hex back to json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json # use json to authenticate with gcloud
    - rm -rf /tmp/$CI_PIPELINE_ID.json # remove creds from server
    - npx gae-ayaml-env # create yaml file with environment variables we need for App Engine
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml # Deploy app to App Engine
    - cd deployment && bash ./migrate.sh # Run migrations

deploy_production:
  stage: production
  image: $DEPLOYER_TAG
  tags:
    - deployer
  when: manual
  only:
    - master
  environment: production
  script:
    - echo $DEPLOYER_SERVICE_ACCOUNT | xxd -r -p - > /tmp/$CI_PIPELINE_ID.json # translate hex back to json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json # use json to authenticate with gcloud
    - rm -rf /tmp/$CI_PIPELINE_ID.json # remove creds from server
    - npx gae-ayaml-env # create yaml file with environment variables we need for App Engine
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml # Deploy app to App Engine
    - cd deployment && bash ./migrate.sh # Run migrations
