image: node:erbium-alpine

variables:
  DEPLOYER_TAG: "registry.gitlab.com/rphovley-templates/node-api-gcae-gcsql-tenancy/deployer"

stages:
  - dependencies
  - build
  - staging
  - production

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  script:
    - yarn
    - yarn lint
  only:
    changes:
      - package.json

deploy_staging:
  stage: staging
  image: $DEPLOYER_TAG
  when: on_success
  environment: staging
  script:
    - echo $DEPLOYER_SERVICE_ACCOUNT | xxd -r -p - > /tmp/$CI_PIPELINE_ID.json # translate hex back to json
    - mkdir server/src/env && mkdir server/src/env/google_service_accounts
    - echo $FIREBASE_SERVICE_ACCOUNT | xxd -r -p - > server/src/env/google_service_accounts/firebase_service_account.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json # use json to authenticate with gcloud
    - rm -rf /tmp/$CI_PIPELINE_ID.json # remove creds from server
    - npx gae-ayaml-env # create yaml file with environment variables we need for App Engine
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml # Deploy app to App Engine

migrate_staging:
  stage: staging
  tags:
    - deployer
  when: on_success
  environment: staging_migrations
  script:
    - sh ./deployment/migrate.sh

deploy_production:
  stage: production
  image: $DEPLOYER_TAG
  when: manual
  only:
    - master
  environment: production
  script:
    - echo $DEPLOYER_SERVICE_ACCOUNT | xxd -r -p - > /tmp/$CI_PIPELINE_ID.json # translate hex back to json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json # use json to authenticate with gcloud
    - rm -rf /tmp/$CI_PIPELINE_ID.json # remove creds from server
    - npx gae-ayaml-env # create yaml file with environment variables we need for App Engine
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml # Deploy app to App Engine

migrate_production:
  stage: production
  tags:
    - deployer
  when: manual
  only:
    - master
  environment: production_migrations
  script:
    - yarn migrate
