version: "3"
services:
  api:
    container_name: api
    image: node:erbium-alpine
    command: /bin/sh -c "cd api && ./node_modules/.bin/nodemon --inspect=0.0.0.0 ./server/dist/server.js"
    volumes:
      - ./server:/api/server
      - ./deployment:/api/deployment
      - ./test/factories:/api/test/factories
      - ./env:/api/env
      - ./node_modules:/api/node_modules
      - ./package.json:/api/package.json
    depends_on:
      - db
    env_file:
      - ./env/.db.env
    ports:
      - "8080:8080"
      - "9229:9229" # for remote debugging
  db:
    container_name: db
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "replace-me"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
