version: "3"
services:
  api:
    container_name: api
    image: node:erbium-alpine
    command: node /api/server/dist/server.js
    env_file:
      - ./server/bin/env/.firebase.env
      - ./server/bin/env/.db.env
      - ./server/bin/env/.log.env
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    container_name: db
    image: postgres:11-alpine
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "global"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
