version: '3'
services:
  api:
    container_name: f0-datalake_api
    command: bash server/bin/wait-for-it.sh api_db npx gulp
    environment:
      NODE_ENV: "development"
      SERVER_PORT: 3030
      API_DB_PORT: 5432
      AUTH_DB_PORT: 5433
    image: gcr.io/fundzero/f0-datalake_api:latest
    volumes:
      - ./:/f0-datalake_api/
    ports:
      - "3030:3030"
      - "9222:9222" # open port for inspector to debug

    depends_on:
      - api_db
      - auth_db

  api_db:
    container_name: f0-datalake_api_db
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "f0-datalake"
    volumes:
      - ./tmp/postgresql-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  auth_db:
    container_name: f0-datalake_auth_db
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "f0-datalake"
    volumes:
      - ./tmp/auth-postgresql-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
