version: "3"
services:
  api:
    container_name: api
    image: node:erbium-alpine
    command: /bin/sh -c "cd api && ./node_modules/.bin/nodemon --inspect=0.0.0.0 ./server/dist/server.js"
    volumes:
      - ./server/dist:/api/server/dist
      - ./server/bin:/api/server/bin
      - ./node_modules:/api/node_modules
      - ./package.json:/api/package.json
    depends_on:
      - global_db
    ports:
      - "8080:8080"
      - "9229:9229" # for remote debugging
  tesla_db:
    container_name: tesla_db
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "tenant"
    volumes:
      - ./data/tesla-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  kwiki_mart_db:
    container_name: kwiki_mart_db
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "tenant"
    volumes:
      - ./data/kwiki-mart-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
  lemonade_stand_db:
    container_name: lemonade_stand_silicon_db
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "tenant"
    volumes:
      - ./data/lemonade-stand-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
  global_db:
    container_name: global_db
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "global"
    volumes:
      - ./data/global-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
